name: Cosmin
version: ${project.version}
main: com.github.sachin.cosmin.Cosmin
api-version: 1.13
depend: [ProtocolLib]
softdepend: [PlaceholderAPI,Vault,PlayerPoints,ItemsAdder,CosmeticsCore,Oraxen,GrimAC,MMOItems]
authors: [ sachingorkar ]
description: Provides two pair of armor slots one for function another for display
commands:
  cosmin:
    description: Core command for cosmin plugin
    permission: cosmin.command.*

permissions:
  cosmin.realarmor:
    description: allows to see other players real armor
    default: false
  cosmin.forceequip.remove:
    description: allows to remove forcefully equiped armor
    default: op
  # cosmin.command.help:
  #   description: allows use of help command
  #   default: op
  # cosmin.command.reload:
  #   description: allows to use reload command
  #   default: op
  # cosmin.command.view:
  #   description: allows to use view command
  #   default: op
  # cosmin.command.give:
  #   description: allows to use give command
  #   default: op
  # cosmin.command.clear:
  #   description: allows to use clear command
  #   default: op
  # cosmin.command.cosmetics:
  #   description: allows to open cosmetic gui
  #   default: true
  cosmin.cosmeticset:
    description: allows to see the cosmetic set button
    default: true
  cosmin.deathdrops.bypass:
    description: bypass permission for drop items on death option
    default: op  
  cosmin.hidearmor.*:
    default: true
    children:
      cosmin.hidearmorhead: true
      cosmin.hidearmorchest: true
      cosmin.hidearmorlegs: true
      cosmin.hidearmorfeet: true
      cosmin.hidearmoroffhand: true
  cosmin.command.*:
    default: op
    children:
      cosmin.command.help: true
      cosmin.command.reload: true
      cosmin.command.view: true
      cosmin.command.give: true
      cosmin.command.clear: true
      cosmin.command.cosmetics: true
      cosmin.command.openwardrobe: true
      cosmin.command.openstore: true
  cosmin.equip.nonmodelitems:
    default: true